repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.9.6
      hooks:
          # Run the linter.
          - id: ruff
            types_or: [python, pyi]
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
            types_or: [python, pyi]
    - repo: local
      hooks:
      - id: isort
        name: isort
        language: system
        types: [python]
        pass_filenames: true
        entry: poetry run isort
      - id: coverage-badge
        name: coverage-badge
        language: system
        types: [python]
        pass_filenames: false
        entry: poetry run task test-badge
        always_run: true
