name: Publish Wheel to Release

on:
  push:
    tags:
      - "v*"

jobs:
  upload-release-asset:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar o zip
        run: choco install zip -y

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install

      - name: Build .whl file
        run: poetry build -f wheel

      - name: Create Release with GitHub CLI
        shell: bash
        run: |
          FILES_WHEEL=$(ls ./dist/*.whl)
          gh release create ${{ github.ref_name }} $FILES_WHEEL --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
