name: Coverage CI  
on: [pull_request]  
  
jobs:  
  poetry:  
    runs-on: ubuntu-latest  
    defaults:  
      run:  
        shell: bash  
  
    strategy:  
      max-parallel: 42   # specify the maximum number of jobs that can run concurrently
      fail-fast: false  
      matrix:  
        python-version: ["3.10"]  
  
    steps:  
      #----------------------------------------------  
      #       check-out repo and set-up python  
      #----------------------------------------------  
      - name: Check out repository  
        uses: actions/checkout@v3  
      - name: Set up python  
        id: setup-python  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
  
      #----------------------------------------------  
      #       install & configure poetry  
      #----------------------------------------------  
      - name: Install and configure Poetry  
        uses: snok/install-poetry@v1  
        with:  
          virtualenvs-create: true  
          virtualenvs-in-project: true  
  
      #----------------------------------------------  
      #       load cached venv if cache exists  
      #----------------------------------------------  
      - name: Load cached venv  
        id: cached-poetry-dependencies  
        uses: actions/cache@v3  
        with:  
          path: .venv  
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}  
  
      #----------------------------------------------  
      #       install dependencies if cache does not exist  
      #----------------------------------------------  
      - name: Install dependencies  
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'  
        run: poetry install --verbose --no-interaction
  
      #----------------------------------------------  
      #       install your root project, if required  
      #----------------------------------------------  
      - name: Install project  
        run: poetry install --verbose --no-interaction  
  
      #----------------------------------------------  
      #       Test coverage  
      #----------------------------------------------  
      - name: Run tests and generate coverage  
        run: |  
          poetry run task test
          poetry run task test-badge